shim-version: v0.1.9@sha256:410510c9e8e4c7489dd201fede302dee8455075ca28f4f0abbf84bded943b8f1
cvm-version: 0.4.1
cpus: 32
memory: 524288
gpus: full
vllm: false

models:
  - name: "llama3-3-70b-fp8"
    repo: "RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic@984c96b73bcf6a675945bac6382b9ed551e5d42b"
    mpk: "0d0be05062e4d3fadc17176cffd1ef6b518a02b0410bd897723f423074ec6cb5_72687374336_99f5f660-3ee0-5626-9772-2f082314e763"
  - name: "qwen3-coder-480b"
    repo: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8@d27784dcbed3a08de523dd74fadff2deb6fedc6b"
    mpk: "bc59459fc1a03ec26049d01854bbb095313f30f4070138a02b33ee653f3bee28_482171310080_d5607439-fe26-5b91-a0c3-4e66642aaea6"

containers:
  - name: "llama3-3-70b-fp8-tp4"
    image: ""
    args: [
      "--runtime", "nvidia",
      "--gpus", "'\"device=0,1,2,3\"'",
      "--ipc", "host",
      "vllm/vllm-openai:v0.9.2",
      "--model", "/tinfoil/mpk/mpk-0d0be05062e4d3fadc17176cffd1ef6b518a02b0410bd897723f423074ec6cb5",
      "--tensor-parallel-size", "4",
      "--served-model-name", "llama3-3-70b",
      "--port", "8001"
    ]
  - name: "qwen3-coder-480b-tp4"
    image: ""
    args: [
      "--runtime", "nvidia",
      "--gpus", "'\"device=4,5,6,7\"'",
      "--ipc", "host",
      "vllm/vllm-openai:v0.10.0",
      "--model", "/tinfoil/mpk/mpk-bc59459fc1a03ec26049d01854bbb095313f30f4070138a02b33ee653f3bee28",
      "--tensor-parallel-size", "4",
      "--gpu-memory-utilization", "0.95",
      "--max-model-len", "128000",
      "--enable-auto-tool-choice",
      "--tool-call-parser", "qwen3_coder",
      "--served-model-name", "qwen3-coder-480b",
      "--port", "8002"
    ]
  - name: "model-router"
    image: ""
    args: [
      "ghcr.io/tinfoilsh/model-router:0.0.1",
      "/app/bin", "-m", "llama3-3-70b_8001,qwen3-coder-480b_8002",
    ]

shim:
  listen-port: 443
  upstream-port: 8087
  publish-attestation: false
  tls-challenge: dns
  control-plane: https://api.tinfoil.sh
  paths:
    - /v1/chat/completions
    - /metrics
  origins:
    - https://tinfoil.sh
    - https://chat.tinfoil.sh
    - http://localhost:3000
